
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module fpga_project
#(
	parameter WIDTH = 32,
	parameter DIVIDER = 1 // Real Run:25
) (

	//////////// CLOCK //////////
	CLOCK_50,

	//////////// LED //////////
	LED,

	//////////// KEY //////////
	KEY,

	//////////// SW //////////
	SW 
);

//=======================================================
//  PARAMETER declarations
//=======================================================
localparam HIGH = DIVIDER + 2; 

//=======================================================
//  PORT declarations
//=======================================================

//////////// CLOCK //////////
input 		          		CLOCK_50;

//////////// LED //////////
output		     [7:0]		LED;

//////////// KEY //////////
input 		     [1:0]		KEY;

//////////// SW //////////
input 		     [3:0]		SW;


//=======================================================
//  REG/WIRE declarations
//=======================================================
reg [WIDTH-1:0] mtime;
wire [2:0] mtimeslice = mtime[HIGH:DIVIDER];

//=======================================================
//  Structural coding
//=======================================================

always @ (posedge CLOCK_50 or negedge KEY[0]) begin
	if (!KEY[0]) mtime <= 'd0;
	else mtime <= mtime + 'd1;
end

assign LED = (KEY[0]) ?(8'd1 << mtimeslice) : 8'd0;

endmodule
