
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module fpga_project(

	//////////// CLOCK //////////
	CLOCK_50,

	//////////// LED //////////
	LED,

	//////////// KEY //////////
	KEY,

	//////////// SW //////////
	SW 
);

//=======================================================
//  PARAMETER declarations
//=======================================================
localparam CLK_DIV = 2; // 2^24 = 16M

//=======================================================
//  PORT declarations
//=======================================================

//////////// CLOCK //////////
input 		          		CLOCK_50;

//////////// LED //////////
output		     [7:0]		LED;

//////////// KEY //////////
input 		     [1:0]		KEY;

//////////// SW //////////
input 		     [3:0]		SW;


//=======================================================
//  REG/WIRE declarations
//=======================================================
reg [CLK_DIV-1 : 0] CLK_DIV_reg = {CLK_DIV{1'b0}};
reg [7:0] led_counter = 8'h00;
// for detect rising
reg clk_1hz_d;

wire clk_1hz =  CLK_DIV_reg[CLK_DIV-1];
wire tick_1hz = clk_1hz & ~clk_1hz_d;

//=======================================================
//  Structural coding
//=======================================================
assign LED = led_counter;

always @(posedge CLOCK_50) begin
	CLK_DIV_reg <= CLK_DIV_reg + 1'b1;
end

always @ (posedge CLOCK_50) begin
	clk_1hz_d <= clk_1hz;
end

always @ (posedge CLOCK_50) begin
	if (tick_1hz) begin
		led_counter <= led_counter + 1'b1;
	end
end

endmodule
