
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module fpga_project 
#(
	parameter WIDTH = 32,
	parameter DIVIDER = 1 // Real Run:25
) (

	//////////// CLOCK //////////
	CLOCK_50,

	//////////// LED //////////
	LED,

	//////////// KEY //////////
	KEY,

	//////////// SW //////////
	SW,

	//////////// SDRAM //////////
	DRAM_ADDR,
	DRAM_BA,
	DRAM_CAS_N,
	DRAM_CKE,
	DRAM_CLK,
	DRAM_CS_N,
	DRAM_DQ,
	DRAM_DQM,
	DRAM_RAS_N,
	DRAM_WE_N,

	//////////// EPCS //////////
	EPCS_ASDO,
	EPCS_DATA0,
	EPCS_DCLK,
	EPCS_NCSO,

	//////////// Accelerometer and EEPROM //////////
	G_SENSOR_CS_N,
	G_SENSOR_INT,
	I2C_SCLK,
	I2C_SDAT,

	//////////// ADC //////////
	ADC_CS_N,
	ADC_SADDR,
	ADC_SCLK,
	ADC_SDAT,

	//////////// 2x13 GPIO Header //////////
	GPIO_2,
	GPIO_2_IN,

	//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
	GPIO_0,
	GPIO_0_IN,

	//////////// GPIO_1, GPIO_1 connect to GPIO Default //////////
	GPIO_1,
	GPIO_1_IN 
);

//=======================================================
//  PARAMETER declarations
//=======================================================


//=======================================================
//  PORT declarations
//=======================================================

//////////// CLOCK //////////
input 		          		CLOCK_50;

//////////// LED //////////
output		     [7:0]		LED;

//////////// KEY //////////
input 		     [1:0]		KEY;

//////////// SW //////////
input 		     [3:0]		SW;

//////////// SDRAM //////////
output		    [12:0]		DRAM_ADDR;
output		     [1:0]		DRAM_BA;
output		          		DRAM_CAS_N;
output		          		DRAM_CKE;
output		          		DRAM_CLK;
output		          		DRAM_CS_N;
inout 		    [15:0]		DRAM_DQ;
output		     [1:0]		DRAM_DQM;
output		          		DRAM_RAS_N;
output		          		DRAM_WE_N;

//////////// EPCS //////////
output		          		EPCS_ASDO;
input 		          		EPCS_DATA0;
output		          		EPCS_DCLK;
output		          		EPCS_NCSO;

//////////// Accelerometer and EEPROM //////////
output		          		G_SENSOR_CS_N;
input 		          		G_SENSOR_INT;
output		          		I2C_SCLK;
inout 		          		I2C_SDAT;

//////////// ADC //////////
output		          		ADC_CS_N;
output		          		ADC_SADDR;
output		          		ADC_SCLK;
input 		          		ADC_SDAT;

//////////// 2x13 GPIO Header //////////
inout 		    [12:0]		GPIO_2;
input 		     [2:0]		GPIO_2_IN;

//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
inout 		    [33:0]		GPIO_0;
input 		     [1:0]		GPIO_0_IN;

//////////// GPIO_1, GPIO_1 connect to GPIO Default //////////
inout 		    [33:0]		GPIO_1;
input 		     [1:0]		GPIO_1_IN;

//=======================================================
//  REG/WIRE declarations
//=======================================================

wire rst_n = KEY[0];

// 1MHz Clock Generator
reg [4:0] clk_1m_cnt;
reg clk_1mhz;

// UART Signals
wire rx_ready;
wire [7:0] rx_data;
wire tx_busy;
wire uart_tx_pin;

// GPIO Bit Bang Signals
wire pa3_out, pa4_out, pa6_out;

// GPIO Assignments
// GPIO_0[0] as UART RX
wire uart_rx_pin = GPIO_0[0];
// GPIO_0[1] as UART TX
assign GPIO_0[1] = uart_tx_pin;

// GPIO_0[2] as 1MHz clock output
assign GPIO_0[2] = clk_1mhz;

// GPIO_0[3] as input pin to read level (output to LED[0] for monitoring)
wire gpio_in_pin = GPIO_0[3];
assign LED[0] = gpio_in_pin;
assign LED[7:1] = 7'b0;

// GPIO_0[4], GPIO_0[5], GPIO_0[6] as bit bang outputs
assign GPIO_0[4] = pa3_out;
assign GPIO_0[5] = pa4_out;
assign GPIO_0[6] = pa6_out;

//=======================================================
//  Structural coding
//=======================================================

// 1MHz Clock Generator (Toggle every 25 cycles of 50MHz clock)
always @(posedge CLOCK_50 or negedge rst_n) begin
	if (!rst_n) begin
		clk_1m_cnt <= 0;
		clk_1mhz <= 0;
	end else begin
		if (clk_1m_cnt == 24) begin
			clk_1m_cnt <= 0;
			clk_1mhz <= ~clk_1mhz;
		end else begin
			clk_1m_cnt <= clk_1m_cnt + 1;
		end
	end
end

// UART RX
uart_rx u_rx (
	.clk(CLOCK_50),
	.rst_n(rst_n),
	.rx(uart_rx_pin),
	.rx_data(rx_data),
	.rx_ready(rx_ready)
);

// UART TX (Loopback)
uart_tx u_tx (
	.clk(CLOCK_50),
	.rst_n(rst_n),
	.tx_start(rx_ready), // Loopback: send data when received
	.tx_data(rx_data), 
	.tx(uart_tx_pin),
	.tx_busy(tx_busy)
);

// GPIO Bit Bang
gpio_bit_bang u_bang (
	.clk(CLOCK_50),
	.rst_n(rst_n),
	.bang_start(SW[0]),
	.bang_data_in(SW[3:1]),
	.pa3(pa3_out),
	.pa4(pa4_out),
	.pa6(pa6_out)
);

endmodule
